name: Build release asset

on:
  release:
    types: [published]

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mpy-cross
      - run: |
          find . -type f -name '*.py' -exec mpy-cross "{}" \;
          find . -type f -name '*.py' -exec rm "{}" \;
          rm -rf .git _docs .gitignore .github README.md
          tar -czf source.tar.gz *

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: source.tar.gz
          asset_name: mpy build source
          asset_content_type: application/gzip
