name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.releases_created }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: simple
          bump-minor-pre-major: true

  mpy-builder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mpy-cross
      - run: |
          find . -type f -name '*.py' -exec mpy-cross "{}" \;
          find . -type f -name '*.py' -exec rm "{}" \;
          rm -rf .git _docs .gitignore .github README.md CHANGELOG.md
#          tar -czf source.tar.gz *

      - name: Compress action step
        uses: a7ul/tar-action@v1.1.3
        id: compress
        with:
          command: c
          files: .
          outPath: source.tar.gz

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: source.tar.gz
          asset_name: source.tar.gz
          asset_content_type: application/gzip
